server:
  port: 9527


spring:
  resources:
  thymeleaf:
    prefix:
      classpath: /templates   # 访问template下的html文件需要配置模板，映射
    cache: false              # 开发时关闭缓存,不然没法看到实时页面
  web:
    resources:
      static-locations:  classpath:templates/,classpath:static/
